spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]': # 匹配所有请求
              allowedOrigins: "*" #跨域处理 允许所有的域
              allowedMethods: # 支持的方法
                - GET
                - POST
                - PUT
                - DELETE
      routes:
            #唯一标识符
            - id: changgou_goods_route
              #用户请求需要路由到该服务[指定要路由的服务]
              #uri: http://localhost:18081
              #代理的服务地址；lb表示从eureka中获取具体服务；Ribbon的@LoadBalanced
              uri: lb://goods
              #路由断言，路由匹配规则
              predicates:
              #用户请求的域名规则配置。所有以cloud.itheima.com的请求都将被路由到http://localhost:18081微服务
              #注意要配置本地C:\Windows\System32\drivers\etc的HOSTS文件 127.0.0.1 cloud.itheima.com
              #- Host=cloud.itheima.com**
              #所有以/goods开始的请求，都路由到http://localhost:18081微服务
              #- Path=/goods/**
              #所有以/api/goods开始的请求，都路由到http://localhost:18081微服务
              - Path=/api/goods**
              filters:
                #添加前缀
                #- PrefixPath=/goods
                #去除前缀
                - StripPrefix=1
                #局部限流器
                - name: RequestRateLimiter #请求数限流 名字不能随便写 ，使用默认的facatory
                  args:
                    #用户身份唯一识别标识符
                    key-resolver: "#{@ipKeyResolver}"
                    #每秒钟只允许一个请求
                    redis-rate-limiter.replenishRate: 1
                    #允许并发有四个请求[宽限的个数]
                    redis-rate-limiter.burstCapacity: 4
            #用户微服务
            - id: changgou_user_route
              uri: lb://user
              predicates:
              - Path=/api/user/**,/api/address/**,/api/areas/**,/api/cities/**,/api/provinces/**
              filters:
                - StripPrefix=1
            #订单微服务
            - id: changgou_order_route
              uri: lb://order
              predicates:
              - Path=/api/cart/**,/api/categoryReport/**,/api/orderConfig/**,/api/order/**,/api/orderItem/**,/api/orderLog/**,/api/preferential/**,/api/returnCause/**,/api/returnOrder/**,/api/returnOrderItem/**
              filters:
                - StripPrefix=1
  application:
    name: gateway-web
server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
management:
  endpoint:
    gateway:
      enabled: true
    web:
      exposure:
        include: true